##merge air quality,greenspace

In [1]:
import pandas as  pd
df1=pd.read_csv("../Data/raw/air_quality_2023.csv")
df2=pd.read_csv("../Data/raw/green_space.csv")

In [ ]:
airquality_greenspace = pd.merge(df1, df2, on='City')

In [ ]:
airquality_greenspace.to_csv("../Data/integrated/airquality_greenspace.csv")

##handle weather_Cairo_csv

In [34]:
df4=pd.read_csv("../Data/raw/weather_cairo.csv")

In [35]:
df4 = df4.rename(columns={
    "date":"Date",
    "temp": "temperature"
})

In [36]:
df4.columns

Index(['Date', 'temperature', 'humidity', 'wind_speed', 'pressure', 'precip'], dtype='object')

In [37]:
df4 = df4.iloc[1:]

In [38]:
df4["City"]="Cairo"

In [19]:
df4.to_csv("../Data/raw/weather_cairo_2023.csv")

In [39]:
print(df4.columns)

Index(['Date', 'temperature', 'humidity', 'wind_speed', 'pressure', 'precip',
       'City'],
      dtype='object')

In [40]:
df4 = df4.drop(columns=['pressure','precip'])

In [41]:




df4.to_csv('../Data/raw/weather_cairo.csv', index=False)

##handle global_weather take from it nairobi,london

In [2]:
df5=pd.read_csv("../Data/raw/global_weather_100_cities_2014_2024.csv")

In [3]:
df5['date'] = pd.to_datetime(df5['date'])

In [4]:
df_2023 = df5[df5['date'].dt.year == 2023]

In [10]:
df_2023["city"].value_counts()

city
Cape Town       365
Casablanca      365
Delhi           365
Johannesburg    365
Lagos           365
London          365
Mexico City     365
Mumbai          365
Nairobi         365
New York        365
Paris           365
Tokyo           365
Name: count, dtype: int64

In [43]:
cities = ['London', 'Nairobi']
df_filtered = df_2023[df_2023['city'].isin(cities)]

In [44]:
df_filtered["city"].value_counts()

city
London     365
Nairobi    365
Name: count, dtype: int64

In [45]:
df_filtered.columns

Index(['date', 'avg_temperature_c', 'avg_humidity_pct', 'rainfall_mm',
       'max_wind_speed_kmh', 'city'],
      dtype='object')

In [46]:
df_filtered = df_filtered.rename(columns={
    'avg_temperature_c': 'Temperature',
    'avg_humidity_pct': 'humidity',
    'city': 'City',
    "max_wind_speed_kmh":"wind_speed"
})

In [47]:
df_filtered = df_filtered.drop(columns=['rainfall_mm'])

In [48]:
df_filtered.sample(10)

            date  Temperature  humidity  wind_speed     City
42908 2023-10-16         20.3        70        16.2  Nairobi
42800 2023-10-07         20.1        60        14.3  Nairobi
42641 2023-09-24         17.0        71        30.6   London
40241 2023-03-08          1.4        96        23.3   London
40976 2023-05-08         19.1        77        10.2  Nairobi
43265 2023-11-15          8.5        84        27.4   London
40088 2023-02-23         21.5        47        20.2  Nairobi
42449 2023-09-08         23.4        67         8.6   London
39737 2023-01-25          0.9        94        20.2   London
41816 2023-07-17         16.3        69         8.5  Nairobi

In [49]:


df_filtered.to_csv('../Data/raw/weather_Nairobi_london.csv', index=False)

In [54]:
df_dubai=pd.read_csv("../Data/raw/dubai_weather_2023.csv")
df_dubai = df_dubai.rename(columns={
    "date":"Date",
    "temp": "Temperature"
})
df_dubai = df_dubai.iloc[1:]
df_dubai = df_dubai.drop(columns=['pressure','precip'])




df_dubai.to_csv('../Data/raw/dubai_weather_2023.csv', index=False)

KeyError: "['pressure', 'precip'] not found in axis"

##dubai

In [59]:
df_newyork = pd.read_csv("../Data/raw/newyork_weather_2023.csv")

df_newyork = df_newyork.rename(columns={
    "date": "Date",
    "temp": "Temperature"
})

df_newyork = df_newyork.drop(columns=['pressure', 'precip'])

df_newyork.to_csv('../Data/raw/newyork_weather_2023.csv', index=False)

In [60]:
df_paris = pd.read_csv("../Data/raw/paris_weather_2023.csv")

df_paris = df_paris.rename(columns={
    "date": "Date",
    "temp": "Temperature"
})
df_paris = df_paris.iloc[1:,]

df_paris = df_paris.drop(columns=['pressure', 'precip'])

df_paris.to_csv('../Data/raw/paris_weather_2023.csv', index=False)

In [61]:
df_tokyo = pd.read_csv("../Data/raw/tokyo_weather_2023.csv")


df_tokyo = df_tokyo.rename(columns={
    "date": "Date",
    "temp": "Temperature"
})
df_tokyo = df_tokyo.iloc[1:,]


df_tokyo = df_tokyo.drop(columns=['pressure', 'precip'])


df_tokyo.to_csv('../Data/raw/tokyo_weather_2023.csv', index=False)

In [14]:
df_jan_ny = df_2023[
    (df_2023['date'].dt.month == 4) & 
    (df_2023['date'].dt.day == 30) & 
    (df_2023['city'].str.lower() == 'new york')
]
df_jan_ny

,date,avg_temperature_c,avg_humidity_pct,rainfall_mm,max_wind_speed_kmh,city
40881,2023-04-30,12.2,96,17.7,27.5,New York